-- create database sellSomething_DB;
-- use sellSomething_DB;
-- create table users (
-- id int auto_increment primary key,
-- user_email varchar(250),
-- password varchar(10)
-- );
-- create table items (
-- id int auto_increment primary key,
-- title varchar(250) not null,
-- categories varchar(100) not null,
-- discription text not null,
-- price int not null
-- )